apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-blog-api
spec:
  selector:
    matchLabels:
      app: go-blog-api
  template:
    metadata:
      labels:
        app: go-blog-api
    spec:
      containers:
      - name: go-blog-api
        image: go-blog-api:dev-20250722T024931Z
        resources:
          requests:
            memory: "128Mi"
            cpu: "25m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        envFrom:
          - secretRef:
              name: go-blog-secret
          - configMapRef:
              name: go-blog-config

